# Generated by Django 6.0.2 on 2026-04-16 22:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ai_provider", models.CharField(default="ollama", max_length=50)),
                (
                    "ollama_base_url",
                    models.CharField(default="http://localhost:11434", max_length=255),
                ),
                ("ollama_model", models.CharField(blank=True, max_length=255)),
                (
                    "lmstudio_base_url",
                    models.CharField(default="http://localhost:1234", max_length=255),
                ),
                ("lmstudio_model", models.CharField(blank=True, max_length=255)),
                ("lmstudio_model_arch", models.CharField(blank=True, max_length=100)),
                ("lmstudio_max_context", models.IntegerField(default=32768)),
                ("gemini_api_key", models.CharField(blank=True, max_length=255)),
                (
                    "gemini_model",
                    models.CharField(default="gemini-2.0-flash", max_length=255),
                ),
                (
                    "llama_server_base_url",
                    models.CharField(default="http://localhost:8012", max_length=255),
                ),
                ("llama_server_model", models.CharField(blank=True, max_length=255)),
                ("ocr_provider", models.CharField(default="mistral", max_length=50)),
                ("mistral_api_key", models.CharField(blank=True, max_length=255)),
                ("reasoning", models.CharField(default="off", max_length=20)),
                ("temperature", models.FloatField(default=0.7)),
                ("max_tokens", models.IntegerField(default=2048)),
                ("zotero_user_id", models.CharField(blank=True, max_length=100)),
                ("zotero_api_key", models.CharField(blank=True, max_length=255)),
                (
                    "zotero_library_type",
                    models.CharField(default="user", max_length=20),
                ),
                ("zotero_api_mode", models.CharField(default="remote", max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("folder", models.CharField(max_length=512)),
                ("criteria", models.TextField()),
                ("zotero_links", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_cancelled", models.BooleanField(default=False)),
                ("load_progress", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PDFJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_path", models.CharField(max_length=512)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("error", "Error"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="article_summary_app.session",
                    ),
                ),
            ],
        ),
    ]
