# Generated by Django 6.0.2 on 2026-04-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article_summary_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
