# Generated by Django 6.0.2 on 2026-04-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article_summary_app", "0002_session_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="zotero_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
