# Generated by Django 6.0.2 on 2026-06-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "article_summary_app",
            "0004_referenceextractionjob_extractedreference_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="referenceextractionjob",
            name="debug_log",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="referenceextractionjob",
            name="raw_llm_response",
            field=models.TextField(blank=True, null=True),
        ),
    ]
