# Generated by Django 6.0.2 on 2026-06-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article_summary_app", "0005_referenceextractionjob_debug_log_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="lmstudio_context_length",
            field=models.IntegerField(default=262144),
        ),
        migrations.AddField(
            model_name="profile",
            name="lmstudio_eval_batch_size",
            field=models.IntegerField(default=262144),
        ),
        migrations.AddField(
            model_name="profile",
            name="lmstudio_flash_attention",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="lmstudio_keep_model_in_memory",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="lmstudio_llama_k_cache_quant_type",
            field=models.CharField(default="false", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="lmstudio_llama_v_cache_quant_type",
            field=models.CharField(default="false", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="lmstudio_num_experts",
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name="profile",
            name="lmstudio_try_mmap",
            field=models.BooleanField(default=True),
        ),
    ]
