# Generated by Django 6.0.2 on 2026-07-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article_summary_app", "0006_profile_lmstudio_context_length_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="referenceextractionjob",
            name="article_doi",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
