# Generated by Django 6.0.2 on 2026-07-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article_summary_app", "0008_profile_core_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlesearch",
            name="debug_log",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="articlesearch",
            name="progress",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
