# Generated by Django 6.0.2 on 2026-07-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article_summary_app", "0009_articlesearch_debug_log_articlesearch_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlesearch",
            name="year_from",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
        migrations.AddField(
            model_name="articlesearch",
            name="year_to",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
    ]
