# Generated by Django 6.0.2 on 2026-07-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article_summary_app", "0010_articlesearch_year_from_articlesearch_year_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlesearch",
            name="filters",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
