# Generated by Django 6.0.2 on 2026-07-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article_summary_app", "0011_articlesearch_filters"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlesearch",
            name="is_paused",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="articlesearch",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("searching", "Searching"),
                    ("searched", "Searched"),
                    ("evaluating", "Evaluating"),
                    ("paused", "Paused"),
                    ("done", "Done"),
                    ("error", "Error"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
