# Generated by Django 6.0.2 on 2026-07-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "article_summary_app",
            "0012_articlesearch_is_paused_alter_articlesearch_status",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="articlesearch",
            name="heartbeat",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
